#  Simulating sales deals

##  Assignment 

Assume that Amir usually works on 3 deals per week, and overall, he wins 30% of deals he works on. Each deal has a binary outcome: it's either lost, or won, so you can model his sales deals with a binomial distribution. In this exercise, you'll help Amir simulate a year's worth of his deals so he can better understand his performance.


In [65]:
import numpy as np

##  Instructions 

- Import `binom` from `scipy.stats` and set the random seed to 10.


In [66]:
from scipy.stats import binom


- Simulate 1 deal worked on by Amir, who wins 30% of the deals he works on.



In [69]:
np.random.seed(10)

In [70]:
binom.rvs(1, 0.3, size=1)

array([1], dtype=int64)


- Simulate a typical week of Amir's deals, or one week of 3 deals.


In [72]:
binom.rvs(3, 0.3, size=1)

array([1], dtype=int64)

- Simulate a year's worth of Amir's deals, or 52 weeks of 3 deals each, and store in `deals`.
- Print the mean number of deals he won per week.


In [74]:
year = binom.rvs(3, 0.3, size=52)

In [75]:
year

array([2, 3, 1, 2, 0, 1, 2, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 2,
       1, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 3, 0, 1, 3, 1, 0,
       1, 1, 2, 0, 1, 1, 1, 1], dtype=int64)

In [76]:
year.mean()

0.8846153846153846

In [77]:
np.mean(year)

0.8846153846153846