
#  Quartiles, quantiles, and quintiles

##  Assignment 

Quantiles are a great way of summarizing numerical data since they can be used to measure center and spread, as well as to get a sense of where a data point stands in relation to the rest of the data set. For example, you might want to give a discount to the 10% most active users on a website.

In this exercise, you'll calculate quartiles, quintiles, and deciles, which split up a dataset into 4, 5, and 10 pieces, respectively. 

Both `pandas` as `pd` and `numpy` as `np` are loaded and `food_consumption` is available.

##  Pre exercise code 

```
import pandas as pd
import numpy as np
food_consumption = pd.read_csv('https://assets.datacamp.com/production/repositories/5786/datasets/49f6356966016c70a9f63a0474942675377bdcf2/food_consumption.csv')
```


In [24]:
import pandas as pd
import numpy as np

In [25]:
food_c = pd.read_csv('food_consumption.csv')

##  Instructions 

- Calculate the quartiles of the `co2_emission` column of `food_consumption`.


In [27]:
np.quantile(food_c['co2_emission'], np.linspace(0, 1, 5))

array([   0.    ,    5.21  ,   16.53  ,   62.5975, 1712.    ])


- Calculate the six quantiles that split up the data into 5 pieces (quintiles) of the `co2_emission` column of `food_consumption`.


In [28]:
np.quantile(food_c['co2_emission'],np.linspace(0, 1, 6))

array([   0.   ,    3.54 ,   11.026,   25.59 ,   99.978, 1712.   ])


- Calculate the eleven quantiles of `co2_emission` that split up the data into ten pieces (deciles).


In [29]:
np.quantile(food_c['co2_emission'], np.linspace(0, 1 , 11))

array([0.00000e+00, 6.68000e-01, 3.54000e+00, 7.04000e+00, 1.10260e+01,
       1.65300e+01, 2.55900e+01, 4.42710e+01, 9.99780e+01, 2.03629e+02,
       1.71200e+03])